global:
  scrape_interval: 15s

rule_files:
  - "alerts.yml"  # Path to the alerting rules file

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['127.0.0.1:9100']

